### ISSUE TITLE
Dropdown of suggestions for search component

### ISSUE THREAD

**Issue by Chasiwpaw** [MikeSmvl/classifieds#25]
I want to see a dropdown of suggestions when I am searching for categories or sub-categories. The suggestions should match the existing categories created. For example, if I am searching for "guitar", the dropdown should show it as I am typing in any subset of the word.

**Comment by darkheros12** [comment]
I have a search algorithm. The problem is I can't find the array of the list of posted items. I need that list so I can search through it. Where are the class for that list and the array of it. All possible help will be appreciated. The code that I currently have does work in some case locally however it can't be done on our project. Thus, you guys can check on searchBarAlgorithms branch.

**Comment by darkheros12** [comment]
This issue is fixed.
